apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_DB
            value: "company"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DB_PASSWORD
        ports:
        - containerPort: 5432
