version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    # check if postgres is initialized and ready to accept connections:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend_app:
    build: .
    container_name: backend_app
    env_file:
      - .env  
    ports:
      - "3000:3000"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
