version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env 
    ports:
      - "5432:5432"
    networks:
      - backend_network

  backend_app:
    build: .
    container_name: backend_app
    env_file:
      - .env  
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
